---
- name: Checking Apache Maven Insrallation
  ansible.builtin.shell: mvn -v
  register: mvn_output
  ignore_errors: true

- name: Removing Apache Maven
  become: yes
  apt:
    name: maven
    state: absent
  when: mvn_output.rc == 0