---
- name: Removing package
  ansible.builtin.include_tasks: oah-remove.yml
  
- name: Getting default conf.
  become: yes
  ansible.builtin.git:
    repo: 'https://github.com/pramit-d/ansible-role-oah-maven.git'
    dest: '{{ mvn_tmp }}'
    clone: yes

- name: Resetting default conf.
  become: yes
  ansible.builtin.copy:
    src: "{{ mvn_tmp }}/defaults/main.yml"
    dest: "{{ role_path }}/defaults/main.yml"
    remote_src: yes

- name: Cleaning up
  become: yes
  file:
    path: "{{ mvn_tmp }}"
    state: absent
  
- name: Installing package
  ansible.builtin.include_tasks: oah-install.yml
